version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-export-model-as-pip-pkg:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./build_and_export_model_as_pip_pkg.sh
          name: Build and Export Model as Pip Package

  build-and-export-model-in-Domino:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python BuildAndExportModelToECR.py
          name: Build and Export Model as Pip Package

workflows:
  main:
    jobs:
      - build-and-export-model-as-pip-pkg
      - build-and-export-model-in-Domino
