version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-model-as-pip-pkg:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./run_tests_prebuild.sh
          name: Test Model as Pip Package

  build-and-export-model-as-pip-pkg:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./build_and_export_model_as_pip_pkg.sh
          name: Build and Export Model as Pip Package

  build-and-export-model-to-ECR:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 BuildAndExportModelToECR.py
          name: Build and Export Model to ECR
          

workflows:
  main:
    jobs:
      - test-model-as-pip-pkg:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/      
#      - build-and-export-model-as-pip-pkg:
#          requires:
#            - test-model-as-pip-pkg
#          filters:
#            tags:
#              only: /^\d+\.\d+\.\d+$/
      - build-and-export-model-to-ECR:
          requires:
            - test-model-as-pip-pkg
            - build-and-export-model-as-pip-pkg
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
