version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-model-as-pip-pkg:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./build_model_as_pip_package.sh
          name: Build Model as Pip Package

workflows:
  main:
    jobs:
      - build-model-as-pip-pkg
      
