version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-export-model-as-pip-pkg:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./build_and_export_model_as_pip_pkg.sh
          name: Build and Export Model as Pip Package

  build-model-in-Domino:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          TEST_VAR: testing

    steps:
     - checkout
     - python/load-cache
     - python/install-deps
     - python/save-cache
#      - run:
#          name: Get Owner ID
#          command: |
#            OWNER_ID=$(curl --location --request GET "https://staging.domino.tech/v4/users/self" --header "Content-Type: application/json" --header "X-Domino-Api-Key: $DOMINO_USER_API_KEY" --data-raw "")
#            echo "OWNER_ID is: $OWNER_ID"

#      - run:
#          name: Get Project ID
#          command: |
#            PROJECT_ID=$(curl --location --request GET "https://staging.domino.tech/v4/projects?name=model-export-demo&ownerId=$OWNER_ID" --header "Content-Type: application/json" --header "X-Domino-Api-Key: $DOMINO_USER_API_KEY" --data-raw "")
#            echo "PROJECT_ID is: $PROJECT_ID"

      - run:
          name: Trigger python code
          command: |
            python3 BuildAndExportModelToECR.py


workflows:
  main:
    jobs:
#      - build-and-export-model-as-pip-pkg
      - build-model-in-Domino
